# Shared HTTP egress-proxy infrastructure. A tool wrapped with
# `network = "proxy"` runs in an isolated network namespace (no external
# interfaces) and reaches the internet ONLY through this proxy, over a
# bind-mounted unix socket — the same cross-netns UDS trick the host-tools-mcp
# broker uses (AF_UNIX is never seccomp-blocked and crosses the netns boundary).
#
# Data path:
#   tool --HTTP(S)_PROXY=http://127.0.0.1:${loopPort}-->
#     in-sandbox  socat 127.0.0.1:${loopPort}  --UNIX-CONNECT--> ${sockPath}
#       host      socat UNIX-LISTEN ${sockPath} --TCP--> 127.0.0.1:${loopPort} (mitmdump)
#         mitmdump (host netns, full internet) --> real destination
#
# The proxy is mitmdump (TLS-INTERCEPTING): it terminates TLS with its own CA,
# logs the decrypted request/response to a readable flows.log, then re-encrypts
# to the real server. The agents trust the CA via SSL_CERT_FILE /
# NODE_EXTRA_CA_CERTS (a bundle = system roots + the mitm CA).
#
# It is an OPEN proxy (no per-domain allowlist): purely the transport, and the
# netns isolation blocks all non-proxied egress (fail-closed — a tool that
# ignores the proxy env reaches nothing).
#
# WARNING: because TLS is intercepted, flows.log contains SECRETS — full URLs,
# Authorization headers / API keys, and request/response bodies (prompts and
# completions). It lives under ~/.cache; treat it as sensitive.
{ pkgs }:
let
  launcher = import ../launcher.nix { inherit pkgs; };

  # Fixed loopback dir (not TMPDIR-derived) so the client and the proxy always
  # agree on the path regardless of either side's TMPDIR. Bind-mounted rw into
  # both sandboxes, layered over bwrap's `--tmpfs /tmp`.
  sockDir = "/tmp/egress-proxy";
  sockPath = "${sockDir}/proxy.sock";
  # Everything user-visible/persistent goes under ~/.cache — a REAL host-backed
  # dir every sandboxed shell binds (zsh base_fs has "$HOME/.cache" rw), so it is
  # shared across all terminals (/tmp is a private per-sandbox tmpfs). These are
  # $HOME-relative strings expanded at runtime (proxyRun / ensure) and at launch
  # (setEnv), since neither mitmdump's config nor bwrap need a build-time literal.
  cacheRel = ".cache/egress-proxy";
  flowsLog = "$HOME/${cacheRel}/flows.log";       # readable request/response dump
  mitmConfDir = "$HOME/${cacheRel}/mitmproxy";     # mitmproxy CA + config live here
  caCert = "${mitmConfDir}/mitmproxy-ca-cert.pem"; # generated by mitmdump on start
  caBundle = "$HOME/${cacheRel}/ca-bundle.crt";    # system roots + mitm CA (tools trust this)
  systemBundle = "${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt";

  # The loopback port mitmdump listens on inside the proxy sandbox, and that the
  # in-sandbox relay listens on inside each tool's (disjoint) netns.
  loopPort = 8118;

  proxyUrl = "http://127.0.0.1:${toString loopPort}";
  proxyEnv = {
    HTTP_PROXY = proxyUrl;
    HTTPS_PROXY = proxyUrl;
    http_proxy = proxyUrl;
    https_proxy = proxyUrl;
  };
  proxyEnvNames = builtins.attrNames proxyEnv;

  # Make the agents trust the mitm CA. SSL_CERT_FILE (OpenSSL) REPLACES the trust
  # store, so it must be the full bundle; NODE_EXTRA_CA_CERTS is additive but a
  # full bundle is harmless. Both point at the runtime-built bundle.
  certEnv = {
    SSL_CERT_FILE = caBundle;
    NODE_EXTRA_CA_CERTS = caBundle;
  };
  certEnvNames = builtins.attrNames certEnv;

  # Merge into a proxied tool's sandbox_restrictions.fs.
  fsEntry = {
    "${sockPath}" = { perm = "rw"; };            # the UDS the tool's relay talks to
  };
  # The CA bundle, read-only, so the tool can validate the intercepted TLS. Built
  # by proxyEnsureCmd before the tool launches (--bind-try tolerates the gap).
  caFsEntry = {
    "${caBundle}" = { perm = "ro"; };
  };

  # Started inside each proxied tool's sandbox (isolated netns) before exec: a
  # loopback listener that forwards to the bind-mounted host UDS. Backgrounded;
  # reaped when the tool (pid 1 in the unshared pidns) exits. The readiness loop
  # waits until the listener accepts before the tool starts making requests.
  mkRelayPrelude = ''
    ${pkgs.socat}/bin/socat TCP4-LISTEN:${toString loopPort},bind=127.0.0.1,reuseaddr,fork UNIX-CONNECT:${sockPath} >/dev/null 2>&1 &
    for _ in $(${pkgs.coreutils}/bin/seq 1 100); do
      (exec 3<>/dev/tcp/127.0.0.1/${toString loopPort}) 2>/dev/null && break
      ${pkgs.coreutils}/bin/sleep 0.05
    done
  '';

  # The proxy: mitmdump (TLS-intercepting, --flow-detail 3 dumps method/URL/
  # headers/text-bodies to flows.log) + the host-side UDS<->TCP bridge. Both run
  # backgrounded; `wait -n` returns when EITHER exits, then we kill both — so a
  # dead mitmdump can never linger behind a live socat (which would look "up" but
  # proxy nothing). Exiting removes the socket, so proxyEnsureCmd restarts it.
  proxyRun = pkgs.writeShellScript "egress-proxy-run" ''
    set -u
    ${pkgs.coreutils}/bin/mkdir -p "$HOME/${cacheRel}"
    ${pkgs.mitmproxy}/bin/mitmdump \
      --set confdir="${mitmConfDir}" \
      --listen-host 127.0.0.1 \
      --listen-port ${toString loopPort} \
      --flow-detail 3 \
      > "${flowsLog}" 2>&1 &
    mp=$!
    ${pkgs.socat}/bin/socat UNIX-LISTEN:${sockPath},fork,mode=0600 TCP4:127.0.0.1:${toString loopPort} &
    so=$!
    wait -n
    kill "$mp" "$so" 2>/dev/null || true
    wait 2>/dev/null || true
  '';

  # The proxy runs through the SAME bwrap sandbox as everything else (no special
  # casing): read-only root, tight fs (writable only under its cache dir), but
  # network = true because it IS the egress point. Detached singleton, so it must
  # outlive the launching client (dont_die_with_parent) and isn't folder-scoped.
  proxyBin = launcher.mkLauncher {
    name = "egress-proxy";
    target = "${proxyRun}";
    keepEnv = [ "HOME" "PATH" "TMPDIR" ];
    setEnv = {};
  };
  proxyWrapper = import ../_wrapper/default.nix {
    name = "egress-proxy";
    inherit pkgs;
    bin = proxyBin;
    sandbox_restrictions = {
      fs = {
        "${sockDir}" = { perm = "rw"; mkdir = true; };
        # Writable: mitmdump's CA/config, flows.log, and the CA bundle live here,
        # where the shells can read them.
        "$HOME/${cacheRel}" = { perm = "rw"; mkdir = true; };
      };
      network = true;
      dont_die_with_parent = true;
    };
    restrict_to_current_folder = false;
    generate_unsafe = false;
    quiet = true;
  };
  proxyBinPath = "${builtins.head proxyWrapper.scripts}/bin/egress-proxy";

  # Host-side (pre-sandbox) auto-start, mirroring brokerEnsureCmd. The health
  # check sends a bare HTTP request through the socket and expects an HTTP reply,
  # so it verifies the FULL chain (socat -> mitmdump), not just that the socket
  # file exists — a stale socket from a killed proxy, or a live socat in front of
  # a dead mitmdump, both fail it and trigger a clean restart. After the proxy is
  # up, (re)build the CA bundle the tools trust (system roots + the mitm CA).
  proxyHealthCheck = "${pkgs.coreutils}/bin/printf 'GET / HTTP/1.0\\r\\n\\r\\n' | ${pkgs.socat}/bin/socat -T2 - UNIX-CONNECT:${sockPath} 2>/dev/null | ${pkgs.gnugrep}/bin/grep -q HTTP/";
  proxyEnsureCmd = ''
    if ! { ${proxyHealthCheck} ; }; then
      ${pkgs.coreutils}/bin/rm -f ${sockPath}
      ${pkgs.util-linux}/bin/setsid -f ${proxyBinPath} >/dev/null 2>&1 || true
      for _ in $(${pkgs.coreutils}/bin/seq 1 300); do
        { ${proxyHealthCheck} ; } && break
        ${pkgs.coreutils}/bin/sleep 0.05
      done
    fi
    # Wait for mitmdump to have written its CA, then (re)build the trust bundle.
    for _ in $(${pkgs.coreutils}/bin/seq 1 100); do
      [ -f "${caCert}" ] && break
      ${pkgs.coreutils}/bin/sleep 0.05
    done
    if [ -f "${caCert}" ]; then
      ${pkgs.coreutils}/bin/cat ${systemBundle} "${caCert}" > "${caBundle}.tmp" \
        && ${pkgs.coreutils}/bin/mv "${caBundle}.tmp" "${caBundle}"
    fi
  '';
in
{
  inherit sockDir sockPath loopPort proxyEnv proxyEnvNames fsEntry
    mkRelayPrelude proxyEnsureCmd certEnv certEnvNames caFsEntry;
}
