#!/bin/sh

if [ $(su ubuntu -c "tmux ls | sed '/^\s*$/d' | wc -l") -eq "0" ]; then
        sleep 60
        if [ $(su ubuntu -c "tmux ls | sed '/^\s*$/d' | wc -l") -eq "0" ]; then
                shutdown -h now
        fi
fi

